/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhocg;

import java.awt.Graphics;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author lucas
 */
public class escolhaDePoligono extends javax.swing.JFrame {

    int flag;
    int numero;
    int pontosX[];
    int pontosY[];
    JPanel panelAux;
    /**
     * Creates new form escolhaDePoligono
     */
    public escolhaDePoligono(int x, JPanel painel) {
        this.panelAux = painel;
        this.numero = x;
        this.pontosX = new int[x];
        this.pontosY = new int[x];
        
        initComponents();
        if(x == 2){//reta
            nomePoligono.setText("Coordenadas da Reta");
            ponto3.setVisible(false);
            ponto3X.setVisible(false);
            ponto3Y.setVisible(false);
            ponto4.setVisible(false);
            ponto4X.setVisible(false);
            ponto4Y.setVisible(false);
            
        }else if(x == 3){//triangulo
            nomePoligono.setText("Coordenadas do Triângulo");
            ponto4.setVisible(false);
            ponto4X.setVisible(false);
            ponto4Y.setVisible(false);
            
        }else if(x == 4){//retangulo
            nomePoligono.setText("Coordenadas do Retângulo");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomePoligono = new javax.swing.JLabel();
        ponto1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ponto2 = new javax.swing.JLabel();
        ponto3 = new javax.swing.JLabel();
        ponto4 = new javax.swing.JLabel();
        ponto1X = new javax.swing.JTextField();
        ponto1Y = new javax.swing.JTextField();
        ponto2Y = new javax.swing.JTextField();
        ponto2X = new javax.swing.JTextField();
        ponto3Y = new javax.swing.JTextField();
        ponto4X = new javax.swing.JTextField();
        ponto4Y = new javax.swing.JTextField();
        ponto3X = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nomePoligono.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nomePoligono.setText("Coordenadas");

        ponto1.setText("Ponto 1:");

        jLabel2.setText("X                   Y");

        ponto2.setText("Ponto 2:");

        ponto3.setText("Ponto 3:");

        ponto4.setText("Ponto 4:");

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ponto4)
                            .addComponent(ponto3)
                            .addComponent(ponto2)
                            .addComponent(ponto1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ponto4X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto3X, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto2X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto1X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ponto1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto2Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto3Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto4Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15))))
                    .addComponent(nomePoligono, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(50, 95, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nomePoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto1Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto2Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto2X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ponto3Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ponto3X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ponto3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto4X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto4Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto4))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(confirmar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        if(numero == 2){
            try {
                this.pontosX[0] = Integer.parseInt(ponto1X.getText());
                this.pontosY[0] = Integer.parseInt(ponto1Y.getText());
                this.pontosX[1] = Integer.parseInt(ponto2X.getText());
                this.pontosY[1] = Integer.parseInt(ponto2Y.getText());
                this.flag = 2;
                Graphics graphics = panelAux.getGraphics();
                graphics.drawLine(this.pontosX[0], 300 - this.pontosY[0], this.pontosX[1], 300 - this.pontosY[1]);//inverter o Quadrante
                //graphics.drawLine(this.pontosX[0], this.pontosY[0], this.pontosX[1], this.pontosY[1]);
                
                
                this.setVisible(false);
            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }else if(numero == 3){
            try {
                this.pontosX[0] = Integer.parseInt(ponto1X.getText());
                this.pontosY[0] = Integer.parseInt(ponto1Y.getText());
                this.pontosX[1] = Integer.parseInt(ponto2X.getText());
                this.pontosY[1] = Integer.parseInt(ponto2Y.getText());
                this.pontosX[2] = Integer.parseInt(ponto3X.getText());
                this.pontosY[2] = Integer.parseInt(ponto3Y.getText());
                for (int i = 0; i < 3; i++) {
                    this.pontosY[i] = 300 - this.pontosY[i];
                }
                Graphics graphics = panelAux.getGraphics();
                graphics.drawPolygon(this.pontosX, this.pontosY, 3);
                this.flag = 2;
                this.setVisible(false);
            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }else if(numero == 4){
            try {
                this.pontosX[0] = Integer.parseInt(ponto1X.getText());
                this.pontosY[0] = Integer.parseInt(ponto1Y.getText());
                this.pontosX[1] = Integer.parseInt(ponto2X.getText());
                this.pontosY[1] = Integer.parseInt(ponto2Y.getText());
                this.pontosX[2] = Integer.parseInt(ponto3X.getText());
                this.pontosY[2] = Integer.parseInt(ponto3Y.getText());
                this.pontosX[3] = Integer.parseInt(ponto4X.getText());
                this.pontosY[3] = Integer.parseInt(ponto4Y.getText());
                for (int i = 0; i < 4; i++) {
                    this.pontosY[i] = 300 - this.pontosY[i];
                }
                //Graphics graphics = panelAux.getGraphics();
                //graphics.drawPolygon(pontosX, pontosY, 4);//drawRect precisa de 1 pontos e altura e largura
                this.flag = 2;
                this.setVisible(false);
            } catch (NumberFormatException ex) {

                JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.flag = 0;
        this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(escolhaDePoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(escolhaDePoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(escolhaDePoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(escolhaDePoligono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nomePoligono;
    private javax.swing.JLabel ponto1;
    private javax.swing.JTextField ponto1X;
    private javax.swing.JTextField ponto1Y;
    private javax.swing.JLabel ponto2;
    private javax.swing.JTextField ponto2X;
    private javax.swing.JTextField ponto2Y;
    private javax.swing.JLabel ponto3;
    private javax.swing.JTextField ponto3X;
    private javax.swing.JTextField ponto3Y;
    private javax.swing.JLabel ponto4;
    private javax.swing.JTextField ponto4X;
    private javax.swing.JTextField ponto4Y;
    // End of variables declaration//GEN-END:variables
}
