/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhocg;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas
 */
public class viewTrabalho extends javax.swing.JFrame {

    enum MouseState {
        MOUSE_NORMAL,
        MOUSE_ROTACAO,
        MOUSE_ESCALA,
        MOUSE_TRANSLACAO
    }

    private MouseState mouseState = MouseState.MOUSE_NORMAL;

    private Optional<Poligono> desenho = Optional.empty();

    private int lastX;
    private int lastY;

    /**
     * Creates new form viewTrabalho
     */
    public viewTrabalho() {
        getContentPane().setBackground(new Color(160,180,220));
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        initComponents();
        painel.setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escalaDialog = new javax.swing.JDialog();
        OK_Escala = new javax.swing.JButton();
        Cancel_Escala = new javax.swing.JButton();
        TextSx = new javax.swing.JFormattedTextField();
        TextSy = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        xRefEscala = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        yRefEscala = new javax.swing.JSpinner();
        escolhaRetaDialog = new javax.swing.JDialog();
        ponto1Y = new javax.swing.JTextField();
        ponto2Y = new javax.swing.JTextField();
        ponto2X = new javax.swing.JTextField();
        nomePoligono = new javax.swing.JLabel();
        ponto1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ponto2 = new javax.swing.JLabel();
        confirmarEscolhaReta = new javax.swing.JButton();
        cancelarEscolhaReta = new javax.swing.JButton();
        ponto1X = new javax.swing.JTextField();
        escolhaTrianguloDialog = new javax.swing.JDialog();
        ponto1Ytri = new javax.swing.JTextField();
        ponto2Ytri = new javax.swing.JTextField();
        ponto2Xtri = new javax.swing.JTextField();
        ponto3Ytri = new javax.swing.JTextField();
        nomePoligono1 = new javax.swing.JLabel();
        ponto3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ponto3Xtri = new javax.swing.JTextField();
        ponto4 = new javax.swing.JLabel();
        confirmarTriangulo = new javax.swing.JButton();
        ponto5 = new javax.swing.JLabel();
        cancelarTriangulo = new javax.swing.JButton();
        ponto1Xtri = new javax.swing.JTextField();
        escolhaRetanguloDialog = new javax.swing.JDialog();
        pontoYret = new javax.swing.JTextField();
        alturaValor = new javax.swing.JTextField();
        nomePoligono2 = new javax.swing.JLabel();
        ponto6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        larguraValor = new javax.swing.JTextField();
        altura = new javax.swing.JLabel();
        confirmarRetangulo = new javax.swing.JButton();
        largura = new javax.swing.JLabel();
        cancelarRetangulo = new javax.swing.JButton();
        pontoXret = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        rotacaoDialog = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        xSpinner = new javax.swing.JSpinner();
        ySpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        angleTxt = new javax.swing.JFormattedTextField();
        rotacaoOK = new javax.swing.JButton();
        rotacaoCancel = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        ImageIcon imgReta = new ImageIcon(getClass().getResource("/imagens/reta.png"));
        drawLine = new javax.swing.JButton("",imgReta);
        ImageIcon imgRetangulo = new ImageIcon(getClass().getResource("/imagens/retangulo.png"));
        drawRect = new javax.swing.JButton("",imgRetangulo);
        ImageIcon imgLimpar = new ImageIcon(getClass().getResource("/imagens/limpar.png"));
        limpar = new javax.swing.JButton("",imgLimpar);
        ImageIcon imgTriangulo = new ImageIcon(getClass().getResource("/imagens/triangulo.png"));
        drawTri = new javax.swing.JButton("",imgTriangulo);
        ImageIcon imgRotacao = new ImageIcon(getClass().getResource("/imagens/rotacao.png"));
        rotacao = new javax.swing.JButton("",imgRotacao);
        ImageIcon imgTranslacao = new ImageIcon(getClass().getResource("/imagens/translacao.png"));
        translacao = new javax.swing.JButton("",imgTranslacao);
        ImageIcon imgEscala = new ImageIcon(getClass().getResource("/imagens/escala.png"));
        escala = new javax.swing.JButton("",imgEscala);
        ImageIcon imgZoomExtend = new ImageIcon(getClass().getResource("/imagens/zoomextend.png"));
        zoomExtend = new javax.swing.JButton("",imgZoomExtend);
        posTxt = new javax.swing.JLabel();

        escalaDialog.setName("escala dialog"); // NOI18N
        escalaDialog.setResizable(false);

        OK_Escala.setText("OK");
        OK_Escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OK_EscalaActionPerformed(evt);
            }
        });

        Cancel_Escala.setText("Cancelar");
        Cancel_Escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_EscalaActionPerformed(evt);
            }
        });

        TextSx.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.###"))));

        TextSy.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.###"))));

        jLabel1.setText("Escala X:");

        jLabel2.setText("Escala Y:");

        jLabel10.setText("Ponto de Referencia:");

        jLabel11.setText("x");

        jLabel12.setText("y");

        javax.swing.GroupLayout escalaDialogLayout = new javax.swing.GroupLayout(escalaDialog.getContentPane());
        escalaDialog.getContentPane().setLayout(escalaDialogLayout);
        escalaDialogLayout.setHorizontalGroup(
            escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escalaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escalaDialogLayout.createSequentialGroup()
                        .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(OK_Escala, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextSx, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cancel_Escala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(escalaDialogLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextSy, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escalaDialogLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xRefEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yRefEscala, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        escalaDialogLayout.setVerticalGroup(
            escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escalaDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(xRefEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yRefEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextSy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escalaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK_Escala)
                    .addComponent(Cancel_Escala))
                .addContainerGap())
        );

        escolhaRetaDialog.setModal(true);
        escolhaRetaDialog.setResizable(false);

        nomePoligono.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nomePoligono.setText("Coordenadas da Reta");

        ponto1.setText("Ponto 1:");

        jLabel3.setText("X                   Y");

        ponto2.setText("Ponto 2:");

        confirmarEscolhaReta.setText("Confirmar");
        confirmarEscolhaReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarEscolhaRetaActionPerformed(evt);
            }
        });

        cancelarEscolhaReta.setText("Cancelar");
        cancelarEscolhaReta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEscolhaRetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escolhaRetaDialogLayout = new javax.swing.GroupLayout(escolhaRetaDialog.getContentPane());
        escolhaRetaDialog.getContentPane().setLayout(escolhaRetaDialogLayout);
        escolhaRetaDialogLayout.setHorizontalGroup(
            escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolhaRetaDialogLayout.createSequentialGroup()
                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escolhaRetaDialogLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, escolhaRetaDialogLayout.createSequentialGroup()
                                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ponto2)
                                    .addComponent(ponto1))
                                .addGap(42, 42, 42)
                                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(escolhaRetaDialogLayout.createSequentialGroup()
                                        .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ponto2X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ponto1X, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ponto1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ponto2Y, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escolhaRetaDialogLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(15, 15, 15))))
                            .addComponent(nomePoligono, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(escolhaRetaDialogLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(confirmarEscolhaReta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(cancelarEscolhaReta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escolhaRetaDialogLayout.setVerticalGroup(
            escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolhaRetaDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nomePoligono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto1Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto1))
                .addGap(18, 18, 18)
                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto2Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto2X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto2))
                .addGap(35, 35, 35)
                .addGroup(escolhaRetaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarEscolhaReta)
                    .addComponent(confirmarEscolhaReta))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        escolhaTrianguloDialog.setModal(true);
        escolhaTrianguloDialog.setResizable(false);

        nomePoligono1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nomePoligono1.setText("Coordenadas do Triangulo");

        ponto3.setText("Ponto 1:");

        jLabel4.setText("X                   Y");

        ponto4.setText("Ponto 2:");

        confirmarTriangulo.setText("Confirmar");
        confirmarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarTrianguloActionPerformed(evt);
            }
        });

        ponto5.setText("Ponto 3:");

        cancelarTriangulo.setText("Cancelar");
        cancelarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escolhaTrianguloDialogLayout = new javax.swing.GroupLayout(escolhaTrianguloDialog.getContentPane());
        escolhaTrianguloDialog.getContentPane().setLayout(escolhaTrianguloDialogLayout);
        escolhaTrianguloDialogLayout.setHorizontalGroup(
            escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ponto5)
                            .addComponent(ponto4)
                            .addComponent(ponto3))
                        .addGap(42, 42, 42)
                        .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ponto3Xtri, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto2Xtri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto1Xtri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ponto1Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto2Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ponto3Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escolhaTrianguloDialogLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15))))
                    .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(confirmarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(cancelarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(nomePoligono1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escolhaTrianguloDialogLayout.setVerticalGroup(
            escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolhaTrianguloDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nomePoligono1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto1Xtri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto1Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto3))
                .addGap(18, 18, 18)
                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ponto2Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto2Xtri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto4))
                .addGap(18, 18, 18)
                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ponto3Ytri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ponto3Xtri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ponto5)))
                .addGap(18, 18, 18)
                .addGroup(escolhaTrianguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarTriangulo)
                    .addComponent(confirmarTriangulo))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        escolhaRetanguloDialog.setModal(true);
        escolhaRetanguloDialog.setResizable(false);

        nomePoligono2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        nomePoligono2.setText("Coordenadas Retangulo");

        ponto6.setText("Ponto:");

        jLabel5.setText("X                   Y");

        larguraValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                larguraValorActionPerformed(evt);
            }
        });

        altura.setText("Altura:");

        confirmarRetangulo.setText("Confirmar");
        confirmarRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarRetanguloActionPerformed(evt);
            }
        });

        largura.setText("Largura:");

        cancelarRetangulo.setText("Cancelar");
        cancelarRetangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRetanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout escolhaRetanguloDialogLayout = new javax.swing.GroupLayout(escolhaRetanguloDialog.getContentPane());
        escolhaRetanguloDialog.getContentPane().setLayout(escolhaRetanguloDialogLayout);
        escolhaRetanguloDialogLayout.setHorizontalGroup(
            escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escolhaRetanguloDialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(confirmarRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(cancelarRetangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(escolhaRetanguloDialogLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(escolhaRetanguloDialogLayout.createSequentialGroup()
                        .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(largura)
                            .addComponent(altura)
                            .addComponent(ponto6))
                        .addGap(42, 42, 42)
                        .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alturaValor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(larguraValor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(escolhaRetanguloDialogLayout.createSequentialGroup()
                                    .addComponent(pontoXret, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(pontoYret, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escolhaRetanguloDialogLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(15, 15, 15)))))
                    .addComponent(nomePoligono2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        escolhaRetanguloDialogLayout.setVerticalGroup(
            escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escolhaRetanguloDialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(nomePoligono2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pontoXret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pontoYret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ponto6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(altura))
                .addGap(18, 18, 18)
                .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(larguraValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(largura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(escolhaRetanguloDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmarRetangulo)
                    .addComponent(cancelarRetangulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rotacaoDialog.setModal(true);
        rotacaoDialog.setResizable(false);

        jLabel6.setText("Ponto de Referencia:");

        jLabel7.setText("x");

        jLabel8.setText("y");

        jLabel9.setText("Ângulo de rotação:");
        jLabel9.setToolTipText("Sentido Anti-horário");

        angleTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        angleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angleTxtActionPerformed(evt);
            }
        });

        rotacaoOK.setText("OK");
        rotacaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotacaoOKActionPerformed(evt);
            }
        });

        rotacaoCancel.setText("Cancelar");
        rotacaoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotacaoCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rotacaoDialogLayout = new javax.swing.GroupLayout(rotacaoDialog.getContentPane());
        rotacaoDialog.getContentPane().setLayout(rotacaoDialogLayout);
        rotacaoDialogLayout.setHorizontalGroup(
            rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotacaoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(rotacaoDialogLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rotacaoDialogLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(angleTxt))
                    .addGroup(rotacaoDialogLayout.createSequentialGroup()
                        .addComponent(rotacaoOK, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rotacaoCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rotacaoDialogLayout.setVerticalGroup(
            rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rotacaoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(xSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(angleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rotacaoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotacaoOK)
                    .addComponent(rotacaoCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        painel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        painel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                painelMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelMouseMoved(evt);
            }
        });
        painel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                painelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        drawLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawLineActionPerformed(evt);
            }
        });

        drawRect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawRectActionPerformed(evt);
            }
        });

        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });

        drawTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawTriActionPerformed(evt);
            }
        });

        rotacao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotacaoActionPerformed(evt);
            }
        });

        translacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                translacaoActionPerformed(evt);
            }
        });

        escala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escalaActionPerformed(evt);
            }
        });

        zoomExtend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomExtendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(posTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drawLine, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drawTri, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drawRect, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(escala, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(translacao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(zoomExtend, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(translacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zoomExtend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drawLine, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(drawRect, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drawTri, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void desenhar() {
        if (!desenho.isPresent()) {
            return;
        }
        Poligono des = desenho.get();

        Graphics g1 = painel.getGraphics();
        g1.setColor(Color.white);
        g1.fillRect(0, 0, painel.getWidth(), painel.getHeight());

        g1.setColor(Color.black);

        double[][] coords = des.transJanelaViewport(painel.getHeight() - 1);

        int[] xs;
        xs = new int[coords[0].length];
        int[] ys;
        ys = new int[coords[0].length];
        for (int i = 0; i < coords[0].length; i++) {
            xs[i] = (int) Math.round(coords[0][i]);
            ys[i] = (int) Math.round(coords[1][i]);
        }

        g1.drawPolygon(xs, ys, coords[0].length);

    }

    private void drawRectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawRectActionPerformed
        escolhaRetanguloDialog.pack();
        escolhaRetanguloDialog.setLocationRelativeTo(null);
        escolhaRetanguloDialog.setVisible(true);
    }//GEN-LAST:event_drawRectActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        painel.repaint();
        painel.setBackground(Color.white);
        desenho = Optional.empty();
    }//GEN-LAST:event_limparActionPerformed

    private void drawTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawTriActionPerformed
        escolhaTrianguloDialog.pack();
        escolhaTrianguloDialog.setLocationRelativeTo(null);
        escolhaTrianguloDialog.setVisible(true);
    }//GEN-LAST:event_drawTriActionPerformed

    private void painelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_painelMouseClicked

    private void drawLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawLineActionPerformed
        escolhaRetaDialog.pack();
        escolhaRetaDialog.setLocationRelativeTo(null);
        escolhaRetaDialog.setVisible(true);
    }//GEN-LAST:event_drawLineActionPerformed

    private void painelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMousePressed
        lastX = evt.getX();
        lastY = evt.getY();
    }//GEN-LAST:event_painelMousePressed

    private void painelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseReleased

    }//GEN-LAST:event_painelMouseReleased

    private void translacaoActionPerformed(java.awt.event.ActionEvent evt) {
        if (mouseState != MouseState.MOUSE_TRANSLACAO) {
            mouseState = MouseState.MOUSE_TRANSLACAO;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.MOVE_CURSOR));
        } else {
            mouseState = MouseState.MOUSE_NORMAL;
            this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }

    private void painelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseDragged
        java.awt.Point pos = evt.getPoint();
        if( 0 <= pos.x && pos.x < painel.getWidth() &&
            0 <= (-pos.y + painel.getHeight()-1) && 
            -pos.y + painel.getHeight()-1 < painel.getHeight()) {
            posTxt.setText(String.format("[%d,%d]", pos.x, -pos.y + painel.getHeight()-1));
        } else {
            posTxt.setText("");
        }

        if (!desenho.isPresent()) {
            return;
        }
        Poligono des = desenho.get();

        int deltaX = (evt.getX() - lastX);
        int deltaY = (evt.getY() - lastY);
        lastX = evt.getX();
        lastY = evt.getY();

        switch (mouseState) {
            case MOUSE_TRANSLACAO:
                if (deltaX != 0 || deltaY != 0) {
                    des.translate(deltaX, -deltaY);
                    desenhar();
                }

                break;
            case MOUSE_NORMAL:
            default:
                break;
        }
    }//GEN-LAST:event_painelMouseDragged

    private void escalaActionPerformed(java.awt.event.ActionEvent evt) {
        escalaDialog.pack();
        escalaDialog.setLocationRelativeTo(null);
        escalaDialog.setVisible(true);
    }

    private void Cancel_EscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_EscalaActionPerformed
        escalaDialog.dispose();
    }//GEN-LAST:event_Cancel_EscalaActionPerformed

    private void OK_EscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OK_EscalaActionPerformed
        if (!desenho.isPresent()) {
            escalaDialog.dispose();
            return;
        }
        Poligono des = desenho.get();

        double Sx = 1.0;
        double Sy = 1.0;
        try {
            NumberFormat fmt = NumberFormat.getInstance();
            Number num = fmt.parse(TextSx.getText());
            Sx = num.doubleValue();
        } catch (NumberFormatException e) {
        } catch (ParseException ex) {
            Logger.getLogger(viewTrabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            NumberFormat fmt = NumberFormat.getInstance();
            Number num = fmt.parse(TextSy.getText());
            Sy = num.doubleValue();
        } catch (NumberFormatException e) {
        } catch (ParseException ex) {
            Logger.getLogger(viewTrabalho.class.getName()).log(Level.SEVERE, null, ex);
        }

        int x = (int) xRefEscala.getValue();
        int y = (int) yRefEscala.getValue();
        
        des.scale(new Ponto2D(x, y), Sx, Sy);
        desenhar();
        
        TextSx.setText("");
        TextSy.setText("");
        xRefEscala.setValue(0);
        yRefEscala.setValue(0);
        escalaDialog.dispose();
    }//GEN-LAST:event_OK_EscalaActionPerformed

    private void rotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotacaoActionPerformed
        rotacaoDialog.pack();
        rotacaoDialog.setLocationRelativeTo(null);
        rotacaoDialog.setVisible(true);
    }//GEN-LAST:event_rotacaoActionPerformed

    private void confirmarEscolhaRetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarEscolhaRetaActionPerformed
        try {
            desenho = Optional.of(
                    new Poligono(new Ponto2D[]{
                new Ponto2D(Integer.parseInt(ponto1X.getText()), Integer.parseInt(ponto1Y.getText())),
                new Ponto2D(Integer.parseInt(ponto2X.getText()), Integer.parseInt(ponto2Y.getText()))
            }));

            desenhar();
            ponto1X.setText("");
            ponto1Y.setText("");
            ponto2X.setText("");
            ponto2Y.setText("");
            escolhaRetaDialog.dispose();
            
        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmarEscolhaRetaActionPerformed

    private void cancelarEscolhaRetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEscolhaRetaActionPerformed
        escolhaRetaDialog.dispose();
    }//GEN-LAST:event_cancelarEscolhaRetaActionPerformed

    private void confirmarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarTrianguloActionPerformed
        try {
            desenho = Optional.of(
                    new Poligono(new Ponto2D[]{
                new Ponto2D(Integer.parseInt(ponto1Xtri.getText()), Integer.parseInt(ponto1Ytri.getText())),
                new Ponto2D(Integer.parseInt(ponto2Xtri.getText()), Integer.parseInt(ponto2Ytri.getText())),
                new Ponto2D(Integer.parseInt(ponto3Xtri.getText()), Integer.parseInt(ponto3Ytri.getText()))
            }));

            desenhar();
            ponto1Xtri.setText("");
            ponto1Ytri.setText("");
            ponto2Xtri.setText("");
            ponto2Ytri.setText("");
            ponto3Xtri.setText("");
            ponto3Ytri.setText("");
            escolhaTrianguloDialog.dispose();
            
        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmarTrianguloActionPerformed

    private void cancelarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarTrianguloActionPerformed
        escolhaTrianguloDialog.dispose();
    }//GEN-LAST:event_cancelarTrianguloActionPerformed

    private void confirmarRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarRetanguloActionPerformed
        try {
            desenho = Optional.of(
                    new Poligono(new Ponto2D[]{
                new Ponto2D(Integer.parseInt(pontoXret.getText()), Integer.parseInt(pontoYret.getText())),
                new Ponto2D(Integer.parseInt(pontoXret.getText()) + Integer.parseInt(larguraValor.getText()), Integer.parseInt(pontoYret.getText())),
                new Ponto2D(Integer.parseInt(pontoXret.getText()) + Integer.parseInt(larguraValor.getText()), Integer.parseInt(pontoYret.getText()) + Integer.parseInt(alturaValor.getText())),
                new Ponto2D(Integer.parseInt(pontoXret.getText()), Integer.parseInt(pontoYret.getText()) + Integer.parseInt(alturaValor.getText()))
            }));

            desenhar();
            
            pontoXret.setText("");
            pontoYret.setText("");
            larguraValor.setText("");
            alturaValor.setText("");
            escolhaRetanguloDialog.dispose();
            
        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "Deve colocar apenas números", "Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmarRetanguloActionPerformed

    private void cancelarRetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRetanguloActionPerformed
        escolhaRetanguloDialog.dispose();
    }//GEN-LAST:event_cancelarRetanguloActionPerformed

    private void painelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseMoved
        java.awt.Point pos = evt.getPoint();
        posTxt.setText(String.format("[%d,%d]", pos.x, -pos.y + painel.getHeight()-1));
    }//GEN-LAST:event_painelMouseMoved

    private void painelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMouseExited
        posTxt.setText("");
    }//GEN-LAST:event_painelMouseExited

    private void rotacaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotacaoOKActionPerformed
        //realizar rotacao sobre desenho
        if(!desenho.isPresent()) {
            rotacaoDialog.dispose();
            return;
        }
        
        double deg = 0;
        try {
            NumberFormat fmt = NumberFormat.getInstance();
            Number num = fmt.parse(angleTxt.getText());
            deg = num.doubleValue();
        } catch (NumberFormatException e) {
        } catch (ParseException ex) {
            Logger.getLogger(viewTrabalho.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        int x = (int)xSpinner.getValue();
        int y = (int)ySpinner.getValue();
        
        Ponto2D ponto = new Ponto2D(x,y);
        
        if(deg != 0) {
            desenho.get().rotateDeg(ponto, deg);
            desenhar();
        }
        
        angleTxt.setText("");
        xSpinner.setValue(0);
        ySpinner.setValue(0);
        
        rotacaoDialog.dispose();
    }//GEN-LAST:event_rotacaoOKActionPerformed

    private void rotacaoCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotacaoCancelActionPerformed
        rotacaoDialog.dispose();
    }//GEN-LAST:event_rotacaoCancelActionPerformed

    private void angleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angleTxtActionPerformed

    private void zoomExtendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomExtendActionPerformed
        if(!desenho.isPresent()) {
            return;
        }
        
        desenho.get().zoomExtend(0,0, painel.getWidth(), painel.getHeight());
        desenhar();
    }//GEN-LAST:event_zoomExtendActionPerformed

    private void larguraValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_larguraValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_larguraValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewTrabalho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new viewTrabalho().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel_Escala;
    private javax.swing.JButton OK_Escala;
    private javax.swing.JFormattedTextField TextSx;
    private javax.swing.JFormattedTextField TextSy;
    private javax.swing.JLabel altura;
    private javax.swing.JTextField alturaValor;
    private javax.swing.JFormattedTextField angleTxt;
    private javax.swing.JButton cancelarEscolhaReta;
    private javax.swing.JButton cancelarRetangulo;
    private javax.swing.JButton cancelarTriangulo;
    private javax.swing.JButton confirmarEscolhaReta;
    private javax.swing.JButton confirmarRetangulo;
    private javax.swing.JButton confirmarTriangulo;
    private javax.swing.JButton drawLine;
    private javax.swing.JButton drawRect;
    private javax.swing.JButton drawTri;
    private javax.swing.JButton escala;
    private javax.swing.JDialog escalaDialog;
    private javax.swing.JDialog escolhaRetaDialog;
    private javax.swing.JDialog escolhaRetanguloDialog;
    private javax.swing.JDialog escolhaTrianguloDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel largura;
    private javax.swing.JTextField larguraValor;
    private javax.swing.JButton limpar;
    private javax.swing.JLabel nomePoligono;
    private javax.swing.JLabel nomePoligono1;
    private javax.swing.JLabel nomePoligono2;
    public javax.swing.JPanel painel;
    private javax.swing.JLabel ponto1;
    private javax.swing.JTextField ponto1X;
    private javax.swing.JTextField ponto1Xtri;
    private javax.swing.JTextField ponto1Y;
    private javax.swing.JTextField ponto1Ytri;
    private javax.swing.JLabel ponto2;
    private javax.swing.JTextField ponto2X;
    private javax.swing.JTextField ponto2Xtri;
    private javax.swing.JTextField ponto2Y;
    private javax.swing.JTextField ponto2Ytri;
    private javax.swing.JLabel ponto3;
    private javax.swing.JTextField ponto3Xtri;
    private javax.swing.JTextField ponto3Ytri;
    private javax.swing.JLabel ponto4;
    private javax.swing.JLabel ponto5;
    private javax.swing.JLabel ponto6;
    private javax.swing.JTextField pontoXret;
    private javax.swing.JTextField pontoYret;
    private javax.swing.JLabel posTxt;
    private javax.swing.JButton rotacao;
    private javax.swing.JButton rotacaoCancel;
    private javax.swing.JDialog rotacaoDialog;
    private javax.swing.JButton rotacaoOK;
    private javax.swing.JButton translacao;
    private javax.swing.JSpinner xRefEscala;
    private javax.swing.JSpinner xSpinner;
    private javax.swing.JSpinner yRefEscala;
    private javax.swing.JSpinner ySpinner;
    private javax.swing.JButton zoomExtend;
    // End of variables declaration//GEN-END:variables
}
